apiVersion: rio.cattle.io/v1
kind: Service
metadata:
  name: autoscale-example
  namespace: default
spec:
  image: gcr.io/knative-samples/autoscale-go:0.1
  imagePullPolicy: Always
  ports:
    - targetPort: 8080
  maxScale: 10
  minScale: 0
  concurrency: 6
  scale: 1