---
apiVersion: rio.cattle.io/v1
kind: Service
metadata:
  name: build-example-revision
  namespace: default
spec:
  build:
    repo: https://github.com/StrongMonkey/demo.git
    revision: 7da55ddc5ac07c4a9ba2c01b78a0d7f15508b54e
  imagePullPolicy: Always
  ports:
    - targetPort: 8080
  scale: 1
---
apiVersion: rio.cattle.io/v1
kind: Service
metadata:
  name: build-example-tag
  namespace: default
spec:
  build:
    repo: https://github.com/StrongMonkey/demo.git
    revision: v0.0.7
  imagePullPolicy: Always
  ports:
    - targetPort: 8080
  scale: 1
---
apiVersion: rio.cattle.io/v1
kind: Service
metadata:
  name: build-example-branch
  namespace: default
spec:
  build:
    repo: https://github.com/StrongMonkey/demo.git
    branch: master
  imagePullPolicy: Always
  ports:
    - targetPort: 8080
  scale: 1
  weight: 100
  rollout: true
  rolloutIncrement: 2
  rolloutInterval: 3
---