apiVersion: rio.cattle.io/v1
kind: Service
metadata:
  name: helloworld-example-v1
  namespace: default
spec:
  app: helloworld-example
  version: v1
  rollout: true
  rolloutIncrement: 2
  rolloutInterval: 3
  image: ibuildthecloud/demo:v1
  imagePullPolicy: Always
  weight: 90
  ports:
    - targetPort: 80
  scale: 1
---
apiVersion: rio.cattle.io/v1
kind: Service
metadata:
  name: helloworld-example-v3
  namespace: default
spec:
  app: helloworld-example
  weight: 10
  rollout: true
  rolloutIncrement: 2
  rolloutInterval: 3
  version: v3
  image: ibuildthecloud/demo:v3
  imagePullPolicy: Always
  ports:
    - targetPort: 80
  scale: 1
---
apiVersion: rio.cattle.io/v1
kind: PublicDomain
metadata:
  name: domain-example
  namespace: default
spec:
  domainName: daishan.do.rancher.space
  targetServiceName: router-example
---
apiVersion: rio.cattle.io/v1
kind: ExternalService
metadata:
  name: external-service-rancher
  namespace: default
spec:
  fqdn: https://www.rancher.com
---
apiVersion: rio.cattle.io/v1
kind: Router
metadata:
  name: router-example
  namespace: default
spec:
  routes:
    - matches:
        - path:
            exact: /to-helloworld
      to:
        - service: helloworld-example
          revision: v1
          namespace: default
          port: 80
          weight: 50
        - service: helloworld-example
          namespace: default
          port: 80
          weight: 50
          revision: v3
    - matches:
        - path:
            exact: /to-helloworld-v1
      to:
        - service: helloworld-example
          revision: v1
          namespace: default
          port: 80
    - matches:
        - path:
            exact: /to-helloworld-v3
      to:
        - service: helloworld-example
          revision: v3
          namespace: default
          port: 80
    - matches:
        - path:
            exact: /to-rancher
      rewrite:
        host: rancher.com
      to:
        - service: external-service-rancher
          namespace: default