configs:
  grafana-dashboardproviders:
    content: |
      apiVersion: 1
      providers:
      - disableDeletion: false
        folder: istio
        name: istio
        options:
          path: /var/lib/grafana/dashboards/istio
        orgId: 1
        type: file
  grafana-datasources:
    content: |
      apiVersion: 1
      datasources:
      - access: proxy
        editable: true
        isDefault: true
        jsonData:
          timeInterval: 5s
        name: Prometheus
        orgId: 1
        type: prometheus
        url: http://prometheus.${PROMETHEUS_NAMESPACE}.svc.cluster.local:9090

services:
  grafana:
    environment:
      - GRAFANA_PORT=3000
      - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_PATHS_DATA=/data/grafana
    image: daishan1992/grafana:latest
    imagePullPolicy: always
    expose:
      - 3000/http
    configs:
      - grafana-dashboardproviders:/etc/grafana/provisioning/dashboards/dashboardproviders.yaml
      - grafana-datasources:/etc/grafana/provisioning/datasources/datasources.yaml
    volumes:
      - data:/data/grafana