configs:
  kiali-config:
    content: |-
      server:
        port: 20001
      external_services:
        grafana:
          url: ${GRAFANA_URL}
services:
  kiali:
    global_permissions:
    - "get,list,watch networking.istio.io/virtualservices"
    - "get,list,watch networking.istio.io/destinationrules"
    - "get,list,watch networking.istio.io/serviceentries"
    - "get,list,watch networking.istio.io/gateways"
    - "get,list,watch config.istio.io/*"
    - "get,list,watch /*"
    - "get,list,watch batch/*"
    - "get,list,watch apps/*"
    - "get,list,watch autoscaling/*"
    image: docker.io/kiali/kiali:v0.19
    env:
    - ACTIVE_NAMESPACE=${NAMESPACE}
    - PROMETHEUS_SERVICE_URL=${PROMETHEUS_URL}
    args:
    - -config
    - /kiali-configuration/config.yaml
    - -v
    - '4'
    configs:
    - kiali-config/content:/kiali-configuration/config.yaml
    secrets:
    - kiali:/kiali-secret/
    ports:
    - 20001/http

kubernetes:
  manifest: |-
    apiVersion: v1
    kind: Secret
    metadata:
      name: kiali
      namespace: ${NAMESPACE}
      labels:
        app: kiali
    type: Opaque
    data:
      username: ${USERNAME}
      passphrase: ${PASSWORD}

templates:
  questions:
  - variable: USERNAME
    description: "username to login dashboard"
  - variable: PASSWORD
    description: "password to login dashboard"
