configs:
  config:
    content: |-
      {
        "nodePathMap": [
          {
            "node": "DEFAULT_PATH_FOR_NON_LISTED_NODES",
            "paths": [
              "/var/lib/rancher/rio/volumes"
            ]
          }
        ]
      }
    labels:
      cattle.io/creator: norman
services:
  local-path-provisioner:
    command:
    - local-path-provisioner
    - --debug
    - start
    - --config
    - /etc/config/config.json
    configs: config:/etc/config/config.json
    environment:
    - POD_NAMESPACE=$(self/namespace)
    global_permissions:
    - nodes
    - persistentvolumeclaims
    - '* endpoints'
    - '* persistentvolumes'
    - '* pods'
    - create,patch events
    - storage.k8s.io/storageclasses
    image: rancher/local-path-provisioner:v0.0.2
