configs:
  autoscale-config:
    content: |-
      enable-scale-to-zero: true
      max-scale-up-rate: 10
      container-concurrency-target-percentage: 1.0
      container-concurrency-target-default: 1
      stable-window: 60s
      panic-window: 6s
      tick-interval: 2s
      scale-to-zero-threshold: 4m
      scale-to-zero-grace-period: 2m

services:
  autoscaler:
    disableServiceMesh: true
    global_permissions:
    - '* configmaps'
    - '* events'
    - get,list,update,watch,delete rio.cattle.io/services
    - get,watch,list,update autoscale.rio.cattle.io/servicescalerecommendations
    - get,watch,list pods
    - get,list,watch,update endpoints
    - get,watch,list services
    image: strongmonkey1992/rio-autoscaler:dev
    imagePullPolicy: always
    ports:
    - 80/http,internal=true
    args:
    - rio-autoscaler
    - gateway
    - --listen
    - '80'
    env:
    - NAMESPACE=$(self/namespace)
    - DEBUG=${DEBUG}

templates:
  questions:
  - variable: DEBUG
    description: "whether to turn on debug"
