services:
  autoscaler:
    global_permissions:
    - '* pods'
    - '* configmaps'
    - '* autoscale.rio.cattle.io/servicescalerecommendations'
    - '* rio.cattle.io/services'
    - '* rio.cattle.io/services/status'
    image: strongmonkey1992/autoscaler:dev
    imagePullPolicy: always
    env:
    - NAMESPACE=${NAMESPACE}
    ports:
    - 80:80,expose=false
    args:
    - --debug

template:
  envSubst: true
