#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p bin
[ "$(uname)" != "Darwin" ] && LINKFLAGS="-extldflags -static -s"
LINKFLAGS="-X github.com/rancher/rio/pkg/version.Version=$VERSION $LINKFLAGS"
LINKFLAGS="-X github.com/rancher/rio/pkg/version.GitCommit=$COMMIT $LINKFLAGS"
LINKFLAGS="-X github.com/rancher/rio/pkg/constants.ControllerImage=${REPO}/rio-controller $LINKFLAGS"
LINKFLAGS="-X github.com/rancher/rio/pkg/constants.ControllerImageTag=${TAG} $LINKFLAGS"
CGO_ENABLED=0 go build -ldflags "$LINKFLAGS" -o bin/rio ./cli
CGO_ENABLED=0 go build -ldflags "$LINKFLAGS" -o bin/rio-controller
