#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p bin
[ "$(uname)" != "Darwin" ] && LINKFLAGS="-extldflags -static -s"
CGO_ENABLED=0 go build -ldflags "-X github.com/rancher/rio/pkg/version.VERSION=$VERSION $LINKFLAGS" -o bin/rio ./cli
CGO_ENABLED=0 go build -ldflags "-X github.com/rancher/rio/pkg/version.VERSION=$VERSION $LINKFLAGS" -o bin/rio-controller
