#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/../package

TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-rancher}

cp ../bin/rio-controller ./rio-controller

IMAGE=${REPO}/rio-controller:${TAG}
docker build -t ${IMAGE} .
mkdir -p ../dist
