---
apiVersion: v1
kind: Namespace
metadata:
  name: rio-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rio-cluster-admin
rules:
- apiGroups:
  - ""
  resources:
  - "*"
  verbs:
  - "*"
- nonResourceURLs:
  - "*"
  verbs:
  - '*'
- apiGroups:
  - "apiregistration.k8s.io"
  resources:
  - "apiservices"
  verbs:
  - "*"
- apiGroups:
  - "admissionregistration.k8s.io"
  resources:
  - "mutatingwebhookconfigurations"
  - "validatingwebhookconfigurations"
  verbs:
  - "*"
- apiGroups:
  - "extensions"
  - "apps"
  resources:
  - "replicasets"
  - "deployments"
  - "daemonsets"
  verbs:
  - '*'
- apiGroups:
  - "autoscale.rio.cattle.io"
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - "build.knative.dev"
  - "caching.internal.knative.dev"
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - "certmanager.k8s.io"
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - "extensions"
  - "networking.k8s.io"
  resources:
  - "ingresses"
  - "ingresses/status"
  verbs:
  - "*"
- apiGroups:
  - "batch"
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - "autoscaling"
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - "admin.rio.cattle.io"
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - "rio.cattle.io"
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - "gitwatcher.cattle.io"
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - "linkerd.io"
  resources:
  - "serviceprofiles"
  verbs:
  - "*"
- apiGroups:
  - "apiextensions.k8s.io"
  resources:
  - "customresourcedefinitions"
  verbs:
  - "*"
- apiGroups:
  - "authentication.istio.io"
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - "networking.istio.io"
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - "config.istio.io"
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - "policy"
  resources:
  - "podsecuritypolicies"
  verbs:
  - "*"
- apiGroups:
  - "rbac.istio.io"
  resources:
  - "*"
  verbs:
  - "get"
  - "watch"
  - "list"
- apiGroups:
  - "autoscaling.internal.knative.dev"
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - "split.smi-spec.io"
  resources:
  - "trafficsplits"
  verbs:
  - "*"
- apiGroups:
  - serving.knative.dev
  - autoscaling.internal.knative.dev
  - networking.internal.knative.dev
  resources:
  - '*'
  - '*/status'
  - '*/finalizers'
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - deletecollection
  - patch
  - watch
- apiGroups:
  - tekton.dev
  resources:
  - tasks
  - clustertasks
  - taskruns
  - pipelines
  - pipelineruns
  - pipelineresources
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - tekton.dev
  resources:
  - taskruns/finalizers
  - pipelineruns/finalizers
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - tekton.dev
  resources:
  - tasks/status
  - clustertasks/status
  - taskruns/status
  - pipelines/status
  - pipelineruns/status
  - pipelineresources/status
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - policy
  resourceNames:
  - tekton-pipelines
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rio-controller-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rio-cluster-admin
subjects:
  - kind: ServiceAccount
    name: rio-controller-serviceaccount
    namespace: rio-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rio-controller-serviceaccount
  namespace: rio-system
---