#!/bin/bash
set -e

cd $(dirname $0)/..

if [[ ${ARCH} == amd64 ]]; then
    echo Running tests

    go test -cover -tags=test ./...

    k3s server >/dev/null 2>&1 &
    sleep 10

    k3s kubectl apply -f ./scripts/rbac.yaml
    export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
    export PATH=$(pwd)/bin:$PATH

    rio-controller >/dev/null 2>&1 &
    rio install --check >/dev/null 2>&1

    go test -v ./tests/integration/... --integration-tests

    cd ./tests
    PROC=$(nproc)
    if [ "$PROC" > 8 ]; then
    PROC=8
    fi
    # todo: set $PROC=1, figure out how to run test in parallel
    PROC=1
    tox -- -n $PROC
    cd ..
fi
