#!/bin/bash
set -e

cd $(dirname $0)/..

fatal()
{
    echo "[ERROR] " "$@"
    exit 1
}

print_log()
{
    EXIT=$?
    if [ $EXIT -ne 0 ]; then
        echo '***RIO LOGS***'
        cat ./rio-controller-log
        echo '***END RIO LOGS***'
    fi
}


if [[ ${ARCH} == amd64 ]]; then
    echo Running tests

    if grep -rnw ./tests/integration/ -e "Focus"; then
      fatal "Integration tests must not be focused"
    fi

    go test -cover -tags=test ./...

    k3s server --no-deploy traefik >/dev/null 2>&1 &
    sleep 30

    export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
    export PATH=$(pwd)/bin:$PATH

    RUN_WEBHOOK=true rio-controller 2>&1 > ./rio-controller-log &
    rio install --check 2>&1

    kubectl get po -n rio-system

    trap print_log exit

    go test -v ./tests/integration/... --integration-tests
fi
