#!/bin/bash
set -e

cd $(dirname $0)/..

fatal()
{
    echo "[ERROR] " "$@"
    exit 1
}


if [[ ${ARCH} == amd64 ]]; then
    echo Running tests

    if grep -rnw ./tests/integration/ -e "Focus"; then
      fatal "Integration tests must not be focused"
    fi

    go test -cover -tags=test ./...

    k3s server >/dev/null 2>&1 &
    sleep 10

    export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
    export PATH=$(pwd)/bin:$PATH

    rio-controller >/dev/null 2>&1 &
    rio install --check >/dev/null 2>&1

    go test -v ./tests/integration/... --integration-tests
fi
